// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230413202203_relacionTipoMercaderia")]
    partial class relacionTipoMercaderia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("int");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaMercaderiaId"));

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("ComandaMercaderiaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MercaderiaId");

                    b.ToTable("ComandaMercaderia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaEntregaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormaEntrega", (string)null);

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "Salon"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "Delivery"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "Pedidos Ya"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MercaderiaId"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("MercaderiaId");

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia", (string)null);

                    b.HasData(
                        new
                        {
                            MercaderiaId = 1,
                            Imagen = "http://drive.google.com/uc?export=view&id=19RZ1fcdX8FaYZapFayXSKkvSeh_eD8sx",
                            Ingredientes = "Berenjenas, vinagre, aceite de oliva, ajo, laurel, orégano, pimentón, sal. ",
                            Nombre = "Berenjenas en Escabeche",
                            Precio = 500,
                            Preparacion = "Cortar las berenjenas y colocarlas en una olla con vinagre y agua. Hervir y colocar las rodajas en un frasco de vidrio esterilizado. Cubrirlas con ajo picado y agregar sal y aceite a gusto. Dejar reposar durante 24 horas antes de consumir.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 2,
                            Imagen = "http://drive.google.com/uc?export=view&id=1xdVsFI-bfmKKrxUOoRvLwNy_tpZi1tlL",
                            Ingredientes = "Porotos, cebolla, ají molido, vinagre, aceite, sal y pimienta. ",
                            Nombre = "Porotos a la vinagreta",
                            Precio = 500,
                            Preparacion = "Saltear la cebolla. Agregar ají molido, el vinagre y cocinar hasta que hierva. En un frasco de vidrio esterilizado, colocar los porotos y cubrir con la mezcla de cebolla. Dejar reposar durante 24 horas antes de consumir.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 3,
                            Imagen = "http://drive.google.com/uc?export=view&id=18PT8STxFOdbqcWPo2qbEeX-dmHqrKL4U",
                            Ingredientes = "Garbanzos cocidos, jugo de limón, aceite de oliva, ajo, sal y comino. ",
                            Nombre = "Humus de Garbanzo",
                            Precio = 500,
                            Preparacion = "Colocar los garbanzos, el jugo de limón, el ajo, el comino, la sal y procesar hasta obtener una pasta suave. Agregar aceite de oliva hasta obtener la consistencia deseada. Servir con tostaditas con ajo.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 4,
                            Imagen = "http://drive.google.com/uc?export=view&id=10KYo-Sx37qfrCCJb2NDwjfBwc0x7k6ya",
                            Ingredientes = "Carne de vaca, pan rallado, huevo, salsa de tomate, jamón, queso y aceite para freír.",
                            Nombre = "Milanesa Napolitana",
                            Precio = 1500,
                            Preparacion = "Desgrasar la carne y dejar reposar en un recipiente con huevo batido, ajo, perejil, sal y pimienta. Pasar por pan rallado. Freír en aceite caliente hasta que esté dorado y crujiente. Cubrir con salsa de tomate, jamón y queso y hornear.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 5,
                            Imagen = "http://drive.google.com/uc?export=view&id=1I1Q6EtlwXY8hCll7GSrXut1aMtjBWCZe",
                            Ingredientes = "Papas, aceite y sal.",
                            Nombre = "Papas Fritas",
                            Precio = 1000,
                            Preparacion = "Pelar y cortar las papas en tiras delgadas. Freír en aceite caliente hasta que estén doradas y crujientes. Escurrir y salar al gusto.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 6,
                            Imagen = "http://drive.google.com/uc?export=view&id=1f-ZxsKFvooSuCWt1KWnX3xn6DnAF4Z88",
                            Ingredientes = "Masa de empanada, carne picada, cebolla, huevo duro, ají molido, sal, cebolla de verdeo.",
                            Nombre = "Empanada",
                            Precio = 400,
                            Preparacion = "Cocinar la carne con cebolla, ají molido y sal. Agregar huevo duro y cebolla de verdero picada. Armar las empanadas y hornear.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 7,
                            Imagen = "http://drive.google.com/uc?export=view&id=1o9q6P2my5mlVrtxmPE-vLHNDv62psRAq",
                            Ingredientes = "Huevos, queso fresco, orégano, sal y pimienta",
                            Nombre = "Omelette",
                            Precio = 900,
                            Preparacion = "Batir los huevos con sal y pimienta. Verter en la sartén antiadherente. Agregar queso y oregano. Enrollar y servir.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 8,
                            Imagen = "http://drive.google.com/uc?export=view&id=11wwHdYe4Zi0eMRrhay3cRzpywlsBbr2a",
                            Ingredientes = "Masa para tarta, jamón, queso, tomate, huevos, sal y pimienta.",
                            Nombre = "Tarta",
                            Precio = 2500,
                            Preparacion = "Estirar la masa para tarta en un molde. Cubrir con jamón, tomate y queso. Batir los huevos con sal y pimienta. Verter sobre la tarta. Cubrir con masa y hornear.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 9,
                            Imagen = "http://drive.google.com/uc?export=view&id=15lJhT2aRy3StYLz76Ikt33Z-ViZaN8nS",
                            Ingredientes = "Fideos, queso crema, queso parmesano, queso roquefort, queso rallado, leche, manteca.",
                            Nombre = "Fideos con salsa cuatro quesos",
                            Precio = 2100,
                            Preparacion = "Cocinar los fideos según las instrucciones del paquete. Mezclar en una sartén la leche con los quesos, a fuego bajo hasta que se derritan. Agregar la manteca y revolver. Servir la salsa sobre los fideos.",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 10,
                            Imagen = "http://drive.google.com/uc?export=view&id=1kYYKJPH865M4a4uoF9FrC0kOkONntdPn",
                            Ingredientes = "Ñoquis, carne picada, cebolla, ajo, tomate, aceite, albahaca, sal y pimienta",
                            Nombre = "Ñoquis con Salsa Bolognesa",
                            Precio = 2500,
                            Preparacion = "Dorar el ajo y agregar cebolla en aceite hasta dorar. Agregar la carne. Agregar tomate picado, albahaca y dejar reducir. Cocinar a fuego bajo. Servir sobre los ñoquis.",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 11,
                            Imagen = "http://drive.google.com/uc?export=view&id=1HujVQHj9rpi4NpW_Dteve04cGO760-Q6",
                            Ingredientes = "Sorrentinos, tomate, cebolla, ajo, aceite, sal y pimienta.",
                            Nombre = "Sorrentinos con Salsa Filetto",
                            Precio = 2500,
                            Preparacion = "Cocinar los sorrentinos según las instrucciones del paquete. En una sartén, dorar cebolla y ajo picados en aceite. Agregar tomate picado y cocinar. Dejar reducir. Cocinar a fuego bajo. Servir sobre los sorrentinos.",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 12,
                            Imagen = "http://drive.google.com/uc?export=view&id=1Zca5YZ3-d9-R9mpBcKJNPloodPNyO5mK",
                            Ingredientes = "Queso provolone, orégano, aceite de oliva.",
                            Nombre = "Provoleta",
                            Precio = 1200,
                            Preparacion = "Cortar el queso en rodajas y rociar con aceite de oliva. Espolvorear orégano. Cocinar a la parrilla o en sartén hasta que esté dorado.",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 13,
                            Imagen = "http://drive.google.com/uc?export=view&id=1KwW_hTxoX1OCaowkrUa4zlWiGwyJONkG",
                            Ingredientes = "Asado, vacio, chorizo, morcilla, chinchulines, riñones, mollejas, sal y limón.",
                            Nombre = "Parrillada para 1",
                            Precio = 2000,
                            Preparacion = "Salar la carne y cocinar en la parrilla a fuego medio. Servir.",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 14,
                            Imagen = "http://drive.google.com/uc?export=view&id=1tjBKJ7w5JIhhw3C3Fi5ZxLu798SSdbIL",
                            Ingredientes = "Asado, vacio, chorizo, morcilla, chinchulines, riñones, mollejas, sal y limón.",
                            Nombre = "Parrillada para 2",
                            Precio = 3000,
                            Preparacion = "Salar la carne y cocinar en la parrilla a fuego medio. Servir.",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 15,
                            Imagen = "http://drive.google.com/uc?export=view&id=1D05vfv2K1VokG5KlXzsxLBLWrqRteAjc",
                            Ingredientes = "Harina, levadura, aceite y sal. Salsa de tomate, ajo, queso muzzarella, aceitunas. ",
                            Nombre = "Muzzarella",
                            Precio = 2300,
                            Preparacion = "Dejar levar la levadura con agua tibia. Mezclar con harina y sal, amasar y dejar reposar untada en aceite. Formar bollos y dejar reposar. Precocinar a la parrilla, agregar salsa de tomate, queso y hornear con bandeja encima. Agregar aceitunas y servir.",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 16,
                            Imagen = "http://drive.google.com/uc?export=view&id=1_FdIEzrM-QS5H78syVAoRX9htrZUCQ7T",
                            Ingredientes = "Harina, levadura, aceite y sal. Tomate, ajo, albahaca, queso muzzarella, aceitunas. ",
                            Nombre = "Napolitana",
                            Precio = 2500,
                            Preparacion = "Levar levadura con agua tibia. Añadir a recipiente con harina y sal. Amasar y dejar reposar untada en aceite. Formar bollos y reposar. Precocinar en parrilla. Agregar salsa, queso y hornear. Añadir tomate, ajo, albahaca, aceitunas. Servir.",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 17,
                            Imagen = "http://drive.google.com/uc?export=view&id=1ekxSyUVbsuGzl00I5bIRYUt0Ntv2bmRC",
                            Ingredientes = "Harina, levadura, aceite y sal. Salsa de tomate, ajo, queso muzzarella, rucula, jamon crudo, tomate cherry, aceitunas negras. ",
                            Nombre = "Rucula y jamon crudo",
                            Precio = 3000,
                            Preparacion = "Levar la levadura, mezclar con harina y sal. Reposar la masa en aceite y tapar. Formar bollos y reposar. Precocinar la masa en parrilla, agregar salsa, queso, bandeja y hornear. Agregar jamón crudo, rúcula, tomate cherry, aceitunas y servir.",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 18,
                            Imagen = "http://drive.google.com/uc?export=view&id=1U_FDLjY-DvNft-6vYpDSwCM50VBdkWmR",
                            Ingredientes = "Harina, levadura, aceite y sal. Queso muzzarella, jamon cocido, cebolla.",
                            Nombre = "Fugazetta Rellena",
                            Precio = 3200,
                            Preparacion = "Dejar levar la levadura con agua tibia. Agregar harina y sal.Amasar y dejar reposar la masa en aceite tapada.Formar bollos y dejar reposar.Extender masa en bandeja.Agregar jamon y queso.Tapar con masa y cebolla.Hornear y servir.",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 19,
                            Imagen = "http://drive.google.com/uc?export=view&id=1MvwhTPB-mIU2U7a_ZEjjgj3QhbMXOJ1B",
                            Ingredientes = "Pan de hamburguesa, carne picada, lechuga, tomate, cebolla, queso cheddar.",
                            Nombre = "Hamburguesa",
                            Precio = 1000,
                            Preparacion = "Mezclar carne picada, ajo, perejil, sal, pimienta, huevo. Formar bolitas con pan rallado. Aplastar y cocinar en parrilla o sartén. Agregar cheddar y dar vuelta. Armar hamburguesa con carne, lechuga, tomate y cebolla en pan.",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 20,
                            Imagen = "http://drive.google.com/uc?export=view&id=1RCO7t5V9v5nMA7mUIMeSzpqDyVDVLWcR",
                            Ingredientes = "Lechuga, cebolla, aceite de giralsol, vinagre de alcohol.",
                            Nombre = "Lechuga y Cebolla",
                            Precio = 700,
                            Preparacion = "Cortar la lechuga en trozos y la cebolla en juliana. Mezclar en un recipiente y agregar aceite, vinagre y sal.",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 21,
                            Imagen = "http://drive.google.com/uc?export=view&id=1AT0FKcyPQ_YGsRma5Ngu6GX8ftf8Ywwd",
                            Ingredientes = "Agua.",
                            Nombre = "Agua",
                            Precio = 500,
                            Preparacion = "Servir en un vaso.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 22,
                            Imagen = "http://drive.google.com/uc?export=view&id=1LgUFou-0XV4ZGXLvl0VdOudpB2xNowUQ",
                            Ingredientes = "Agua con gas.",
                            Nombre = "Agua con gas",
                            Precio = 500,
                            Preparacion = "Servir en un vaso.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 23,
                            Imagen = "http://drive.google.com/uc?export=view&id=19_2s9DOCYfjSeOM8oOMjfPLZQxrIbrax",
                            Ingredientes = "CocaCola.",
                            Nombre = "CocaCola",
                            Precio = 700,
                            Preparacion = "Servir en un vaso.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 24,
                            Imagen = "http://drive.google.com/uc?export=view&id=1GPpCuTHDb_YfZ5WgfBpwnh6gCZ4UzYh9",
                            Ingredientes = "Agua Tonica",
                            Nombre = "Agua Tonica",
                            Precio = 700,
                            Preparacion = "Servir en un vaso.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 25,
                            Imagen = "http://drive.google.com/uc?export=view&id=17DJ0vDYpvAlRvFtfor2hVXmB3nb6p5KK",
                            Ingredientes = "Vino de la casa.",
                            Nombre = "Vino",
                            Precio = 2000,
                            Preparacion = "Servir en una copa.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 26,
                            Imagen = "http://drive.google.com/uc?export=view&id=1SdRfF1u3J6ejfsoYoMIiXLSaplHcNaDS",
                            Ingredientes = "Maltas claras, lupulos suaves y agua.",
                            Nombre = "Blonde Ale",
                            Precio = 700,
                            Preparacion = "Se mezclan los ingredientes en agua caliente para producir mosto. Luego se agrega levadura para la fermentación, y después de algunos días, se empaqueta en barriles para la carbonatación. Finalmente, se enfría y se sirve.",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 27,
                            Imagen = "http://drive.google.com/uc?export=view&id=1uNGK3SZOYrbb4SkF9TZpEhw-qQ1i_6Su",
                            Ingredientes = "Maltas oscuras, lupulos amargos, agua y miel.",
                            Nombre = "Honey",
                            Precio = 700,
                            Preparacion = "Se mezclan los ingredientes en agua caliente para producir mosto. Luego se agrega levadura para la fermentación, y después de algunos días, se empaqueta en barriles para la carbonatación. Finalmente, se enfría y se sirve.",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 28,
                            Imagen = "http://drive.google.com/uc?export=view&id=1dupPwq4BpsOAfeloQt0zncUPgS5b8TSL",
                            Ingredientes = "Maltas palidas, lupulos fuertes y agua.",
                            Nombre = "Scottish",
                            Precio = 700,
                            Preparacion = "Se mezclan los ingredientes en agua caliente para producir mosto. Luego se agrega levadura para la fermentación, y después de algunos días, se empaqueta en barriles para la carbonatación. Finalmente, se enfría y se sirve.",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 29,
                            Imagen = "http://drive.google.com/uc?export=view&id=1ElTRsSRJST0nTWKSsfQkR4XSeNhlI6Al",
                            Ingredientes = "Pan, leche, huevos, azúcar, pasas de uva, esencia de vainilla. ",
                            Nombre = "Budin de Pan",
                            Precio = 800,
                            Preparacion = "Remojar el pan en la mezcla de leche, huevos, azúcar y vainilla. Agregar pasas y hornear.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 30,
                            Imagen = "http://drive.google.com/uc?export=view&id=1wq625i2tDiHzQRVGrU_i3hYJpzuPwryc",
                            Ingredientes = "Helado, salsa de chocolate y crema. ",
                            Nombre = "Copa Helada",
                            Precio = 800,
                            Preparacion = "Colocar el helado en una copa y cubrir con la salsa de chocolate. Agregar crema batida.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 31,
                            Imagen = "http://drive.google.com/uc?export=view&id=1Jmqg2GaZ0Whmq-yzxgtNOOBCi8k2dIwL",
                            Ingredientes = "Harina, leche, huevos, sal, dulce de leche. ",
                            Nombre = "Panqueques con dulce de leche",
                            Precio = 800,
                            Preparacion = "Batir leche, huevo y harina con una pizca de sal. Cocinar en sartén caliente. Untar con dulce de leche y enrollar.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 32,
                            Imagen = "http://drive.google.com/uc?export=view&id=1NX-GToSUk1pqMHpU6K0r453GlJOt3HH4",
                            Ingredientes = "Frutillas, crema batida, azúcar. ",
                            Nombre = "Frutillas con Crema",
                            Precio = 800,
                            Preparacion = "Cortar las frutillas, agregar azúcar y dejar reposar. Servir con crema batida.",
                            TipoMercaderiaId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMercaderiaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia", (string)null);

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "Entrada"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "Minutas"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "Pastas"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "Parrilla"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "Sandwich"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "Ensaladas"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "Bebidas"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "Cerveza Artesanal"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "Postres"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.HasOne("Domain.Entities.FormaEntrega", "FormaEntrega")
                        .WithMany("Comandas")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaEntrega");
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.HasOne("Domain.Entities.Comanda", "Comanda")
                        .WithMany("ComandaMercaderias")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mercaderia", "Mercaderia")
                        .WithMany("ComandaMercaderias")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.HasOne("Domain.Entities.TipoMercaderia", "TipoMercaderia")
                        .WithMany("Mercaderias")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Navigation("ComandaMercaderias");
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Navigation("ComandaMercaderias");
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Navigation("Mercaderias");
                });
#pragma warning restore 612, 618
        }
    }
}
